```{r message=FALSE, warning=FALSE}
library(dplyr)
```


```{r}
df<-read.csv("car_evaluation.csv")
```


```{r}
unique(df$buying)
```


```{r}
buyingFactor<-factor(df$buying,levels = c("low","med","high","vhigh"),labels = c(0,1,2,3))
```


```{r}
unique(df$maint)
```


```{r}
maintFactor<-factor(df$maint,levels = c("low","med","high","vhigh"),labels = c(0,1,2,3))
```


We assign the highest numerical value. For the highest category.


```{r}
unique(df$doors)
```

It seems that the doors variable is numeric. But since this column has a category with a text nature. So R performs a standardization. And transforms it as a character variable.


```{r}
doorsFactor<-factor(df$doors,levels = c("2","3","4","5more"),labels = c(2,3,4,5))
```



```{r}
unique(df$persons)
```

```{r}
personsFactor<-factor(df$persons,levels = c("2","4","more"),labels = c(2,4,5))
```

We do a similar process as the previous case.


```{r}
unique(df$lug_boot)
```
```{r}
lugbootFactor<-factor(df$lug_boot,levels = c("small","med","big"),labels = c(0,1,2))
```


```{r}
unique(df$safety)
```

```{r}
safetyFactor<-factor(df$safety,levels = c("low","med","high"),labels = c(0,1,2))
```



```{r}
unique(df$class)
```

```{r}
classFactor<-factor(df$class,levels = c("unacc","acc","vgood","good"),labels = c(0,1,2,3))
```


### Variable Transformation


```{r}
dfClear<-df %>%
  
  mutate(buying=buyingFactor,
         maint=maintFactor,
         doors=doorsFactor,
         persons=personsFactor,
         lug_boot=lugbootFactor,
         safety=safetyFactor,
         class=classFactor)
```



## Save CSV File


```{r}
write.csv(dfClear,file="Car_Evaluation_Clear.csv",row.names = F)
```

